### ISSUE TITLE
create an index creation function

### ISSUE THREAD

**Issue by soltanianalytics** [Gemma-Analytics/gemma-dbt-utils#2]
Goal: Have a function for standardized index creation to be used in the `dbt_project.yml` or model configurations like to:

```yaml
models:
  analytics:
    post-hook: '{{ gemma_dbt_utils.post_hook_index("column_name") }}'
    post-hook: '{{ gemma_dbt_utils.post_hook_index_id() }}'
```

The syntax should follow this approach: `create index if not exists {{ this.name }}__index_on_id on {{ this }} ("id")`. `post_hook_index_id()` should just call `post_hook_index("id")`.
